version: 2
updates:
- package-ecosystem: cargo
  directory: "/fitsio"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  groups:
    cargo-packages:
      patterns:
        - "*"
- package-ecosystem: cargo
  directory: "/fitsio-derive"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  groups:
    cargo-packages:
      patterns:
        - "*"
- package-ecosystem: cargo
  directory: "/fitsio-sys"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  groups:
    cargo-packages:
      patterns:
        - "*"
- package-ecosystem: cargo
  directory: "/fitsio-sys-bindgen"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  groups:
    cargo-packages:
      patterns:
        - "*"
  ignore:
  - dependency-name: bindgen
    versions:
    - 0.56.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  groups:
    cargo-packages:
      patterns:
        - "*"
