[package]
name = "fitsio-src-fetcher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.34", features = ["derive"] }
reqwest = { version = "0.12.15", features = ["blocking"] }
tempfile = "3.19.1"
